name: Release

on:
  push:
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '19.0.0'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm install -g expo-cli
          npx expo install --fix
          
      - name: Build Expo web
        run: npx expo export:web
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          
      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: web-build/
          retention-days: 30 