name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: --max_old_space_size=4096

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '19.0.0'
        cache: 'npm'
    
    - name: Install Expo CLI
      run: npm install -g expo-cli
    
    - name: Install dependencies
      run: |
        npm ci
        npx expo install --fix
      
    - name: Run tests
      run: npm run test
      
    - name: Upload test coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: coverage/
        retention-days: 30 